**INSTRUCTIONS:**

Go to File -> Save a Copy in Drive and edit this notebook in your copy

 Put all your doubts on Discord channel

Do not plagiarise


In [1]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [2]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [3]:
X = np.array([[1, 2], [3, 4]])
matrix = np.asmatrix(X)

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [4]:
np.linspace(3,10,50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [5]:
x = np.array([[1,2,3],[4,5,6]])
np.reshape(x, 6, order = 'F')

array([1, 4, 2, 5, 3, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.





In [6]:
x = [1,2,3,4,5,6,7,8,9]
np.array_split(x, [4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [7]:
x = np.array([[1,2],
             [3,4]])
print(np.linalg.inv(x)) # printing inverse
print(np.trace(x)) # printing sum of primary diagonal elements (Trace)

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [8]:
x = np.array([[1,4],[3,1]])
np.sort(x, axis = 1)

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [9]:
np.argsort(x, axis = 1)

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [10]:
x = np.random.uniform(0,10, size = (2,5))
print(x)
max = x.max()
min = x.min()
print("max value = ", max,", min value = ", min)
index_max = np.unravel_index(np.argmax(x, axis = None), x.shape)
index_min = np.unravel_index(np.argmin(x, axis = None), x.shape)
print("indices of max value = ", index_max,", indices of min value = ", index_min)

[[3.25889505 0.30701856 9.70507284 9.75750328 4.97267539]
 [1.13411296 1.49169961 1.0446129  2.3990771  9.95022233]]
max value =  9.95022232505901 , min value =  0.30701855805752576
indices of max value =  (1, 4) , indices of min value =  (0, 1)


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [11]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [12]:
for row in iris_2d:
  for data in row:
    if(np.isnan(data) == 'True'):
      np.delete(row)
      break

Find the correlation between first two columns.

In [13]:
np.corrcoef(iris_2d[:,0], iris_2d[:,1])

array([[ 1.        , -0.10936925],
       [-0.10936925,  1.        ]])

Find the mean,median and standard deviation of column 3.

In [14]:
mean = np.mean(iris_2d[:,2])
median = np.median(iris_2d[:,2])
std = np.std(iris_2d[:,2])
print("mean = ", mean, ", median = ", median, ", standard deviation = ", std)

mean =  3.758666666666666 , median =  4.35 , standard deviation =  1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [15]:
volume = []
for i in range(np.shape(iris_2d)[0]):
  pi = np.pi
  sepal_len = iris_2d[i][0]
  petal_len = iris_2d[i][2]
  data = (pi * petal_len * sepal_len * sepal_len)/3
  volume.append(data)
volume = np.reshape(np.array(volume), (np.shape(iris_2d)[0],1))
iris_2d = np.append(iris_2d, volume, axis=1)
iris_2d

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.7000

Run the following loaad command and solve the following questions

In [16]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [17]:
species = np.unique(iris[:,4])
count = np.shape(species)[0]
count

3

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [18]:
bins = [0,3,5,iris_2d[:,2].max()]
indices = np.digitize(iris_2d[:,2], bins)
petal_len_cat = []
for i in indices:
  if(i==1):
    petal_len_cat.append("small")
  elif(i==2):
    petal_len_cat.append("medium")
  else:
    petal_len_cat.append("large")
petal_len_cat = np.array(petal_len_cat)
petal_len_cat

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium

Find the most frequent value of petal length (3rd column) in iris dataset

In [19]:
values, counts = np.unique(iris[:,2], return_counts = True)
index_max = np.argmax(counts)
values[index_max]

b'1.5'